### ISSUE TITLE
Install using setup.py

### ISSUE THREAD

**Issue by Shravya-Raju** [thegeorgeous/flask-cqlalchemy#1]
I am trying to install this package in my app setup.py and it fails to install as it cannot find 0.2.0 version in pypi.python.org/simple. Can you please make it work?

My app setup.py:

install_requires = [
        'Flask-CQLAlchemy==0.2.0',
]

---

Searching for Flask-CQLAlchemy==0.2.0
Reading https://pypi.python.org/simple
Reading https://pypi.python.org/simple/Flask-CQLAlchemy/
No local packages or download links found for Flask-CQLAlchemy==0.2.0
error: Could not find suitable distribution for Requirement.parse('Flask-CQLAlchemy==0.2.0')

**Comment by thegeorgeous** [comment]
Are you able to run `pip install Flask-CQLAlchemy==0.2.0`?

**Comment by thegeorgeous** [comment]
It seems install_requires still uses Eggs and not Wheels. I have uploaded the Egg for the version. Please check now.

**Comment by Shravya-Raju** [comment]
Hello George,

Egg 0.2.0 works great!
Yes, pip install flask-cqlalchemy==0.2.0 worked. That's how I installed the extension initially. But, I am using setup.py for all other packages so need an Egg 0.2.0 for your package. I read more about wheels yesterday and looks like its more common on PyPI these days. Hoping that setup.py will soon add that capability to install wheels. 

Thanks!

**Comment by thegeorgeous** [comment]
Great! closing the issue then
