### ISSUE TITLE
db.UserType no module

### ISSUE THREAD

**Issue by n3011** [thegeorgeous/flask-cqlalchemy#11]
Is it possible to incorporate db.usertype module?

**Comment by thegeorgeous** [comment]
did you mean User Defined Types? http://datastax.github.io/python-driver/cqlengine/models.html#user-types

I've been meaning to add them, just haven't gotten around to doing it. You can expect them soon though. Cheers!

**Comment by n3011** [comment]
yah exactly! Thanks.

**Comment by thegeorgeous** [comment]
@n3011, would it be possible for you to test this PR #12 and check if User Types work as intended?

**Comment by thegeorgeous** [comment]
Added in [v1.2.0](https://github.com/thegeorgeous/flask-cqlalchemy/releases/tag/v1.2.0)
