### ISSUE TITLE
Add automated PyPI deployments via Travis

### ISSUE THREAD

**Issue by thegeorgeous** [thegeorgeous/flask-cqlalchemy#22]
Travis CI can automatically release a Python package to PyPI after a successful build. For this to be a viable option it must be able to create both wheel and egg distributions since wheel distributions are not supported by `setup_tools`

**Comment by Richard-Mathie** [comment]
giving this a go now.
see edc0cb42e5bc8119c52522b4670b1be9a88c214f

**Comment by thegeorgeous** [comment]
Closing this since we have moved on from Travis to Github Actions
