### ISSUE TITLE
I run this install flask-cqlalchemy 

### ISSUE THREAD

**Issue by Ahmad31** [thegeorgeous/flask-cqlalchemy#26]
Command "/var/www/app_arsip/flask/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-zuvskE/blist/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-qYK0Yo-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/app_arsip/flask/include/site/python2.7/blist" failed with error code 1 in /tmp/pip-build-zuvskE/blist/

**Comment by Richard-Mathie** [comment]
pip failed to install blist

perhaps you need gcc and python-dev

though blist should have been removed as a dependency

**Comment by Ahmad31** [comment]
Hi Richard-Mathie thanks for your answer it's been working,
I have another problem, can you give me a hint how to create a search form using these flasks-cqlalchemy ?
thank you
