### ISSUE TITLE
Flask-CQLAlchemy DB objects dont have 'query' attribute

### ISSUE THREAD

**Issue by sourabhsriom** [thegeorgeous/flask-cqlalchemy#31]
I am trying to write a flask application with Cassandra. I am using the Flask-CQLAlchemy library to do this and the basic querying supported by the ORM doesn't seem to work.

My code looks something like this :

```
from flask_cqlalchemy import CQLAlchemy
from flask import Flask

db = CQLAlchemy(app)

class Person(db.Model):
    id = db.columns.UUID(primary_key=True)
    first_name  = db.columns.Text()
    last_name = db.columns.Text()
```
When I open up the terminal and go to Python, I create a new person with

`person1 = Person(first_name='ABC', last_name='WYZ')`
It goes through but when I query the Person database with :

`Person.query.limit(1).all()`
I get an error saying :

`AttributeError: type object 'Person' has no attribute 'query'`

Is there something else that needs to be added in the CQLAlchemy program? If this code is write then is there another way to query data?

**Comment by jacobbaker** [comment]
Try: `Person.objects().limit(1).all()` that should work?

https://docs.datastax.com/en/drivers/python/2.5/api/cassandra/cqlengine/query.html

**Comment by sourabhsriom** [comment]
thanks @jacobbaker That is the issue.

**Comment by thegeorgeous** [comment]
@sourabhsriom, closing this issue. Please reopen if necessary.
