### ISSUE TITLE
Release the new PyPi version and support for Python 3.10

### ISSUE THREAD

**Issue by onix** [thegeorgeous/flask-cqlalchemy#34]
Hi, we are trying to migrate our Flask application from Python 3.9 to 3.10 and pip install fails while compiling the `blist` dependency with a clang code error:

```
    blist/_blist.c:5403:23: warning: comparison of integers of different signs: 'Py_ssize_t' (aka 'long') and 'unsigned long' [-Wsign-compare]
            for (j = 0; j < NUM_PASSES; j++) {
                        ~ ^ ~~~~~~~~~~
    blist/_blist.c:6592:27: error: expression is not assignable
            Py_REFCNT(&saved) = 1;
            ~~~~~~~~~~~~~~~~~ ^
    4 warnings and 1 error generated.
    error: command '/usr/bin/clang' failed with exit code 1
```

Looking through the recent commit history I found you have removed `blist` dependency and bumped app version to 1.3.0 but no new version in PyPi was released. Do you plan to release a new version to PyPi and possibly add support for the recent Python version?

Python tested version: 3.10.0, 3.10.1
Flask 2.0.2
cassandra-driver 3.25.0
(blist==1.3.6)

**Comment by thegeorgeous** [comment]
@onix 

I'll release the 1.3.0 in the next couple of days. Adding support for the newer Python versions may take longer.

**Comment by onix** [comment]
@thegeorgeous good to hear that! As for newer versions I can only say we have been using your lib in a Flask application with a simple C* CRUD operations somewhere since Python 3.6 and all that time it worked fine.

Perhaps, I could assist you, but have no idea about versioning/testing strategy. Try to make own CI instance and play with forked .travis.yml? Have never worked with this yet.

**Comment by onix** [comment]
Hi, created a pull request that covers the second part of my request -- #35 , moved the CI to Github Actions and ensured everything works (tests run) on new versions.

How the actions work you can ensure with my latest runs https://github.com/onix/flask-cqlalchemy/actions

There is also a PyPi publishing workflow in Actions Templates but did not get to this -- it also needs a PyPi API token I have no access to. Perhaps later will try this for some dummy package.

**Comment by shanyas10** [comment]
Hi, has there been a fix to this since we have been facing this issue with Python 3.10

**Comment by thegeorgeous** [comment]
@onix Thank you for the contribution. It has been challenging to find time for this. 

Since the PR breaks backwards compatibility, I've bumped up the version and released v2.0.0. Let me know if this resolves this issue and I'll close it.

**Comment by thegeorgeous** [comment]
@shanyas10 could you please try the new version and see if that resolves your issue?

**Comment by onix** [comment]
Hi @thegeorgeous you're welcome! We've updated our small prod app to v2.0 since 10 February and it still works great :)

Now I am testing with Python 3.11, but looks it works also fine, definitely without (binary module) installation issues.
